name: mirror_docker_image
on:
  issues:
    types: [opened]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Check issue's title
        id: check-title
        run: |
          if echo ${{ github.event.issue.title }} | grep -qE "^(.+\/)([a-z0-9_\-]+):.+$"; then
            echo ::set-output name=match::true
            echo ::set-output name=image_tag::$(echo ${{ github.event.issue.title }} | grep -oE "([a-z0-9_\-]+):.+$")
            echo ::set-output name=image::$(echo ${{ github.event.issue.title }} | grep -oE "([a-z0-9_\-]+):.+$" | awk -F ':' '{print $1}')
          else
            echo ::set-output name=match::false
          fi

      - name: Checkout
        if: steps.check-title.outputs.match == 'true'
        uses: actions/checkout@v2

      - name: Add label
        if: steps.check-title.outputs.match == 'true'
        uses: andymckay/labeler@master
        with:
          add-labels: "docker_image"

      - name: Pull image
        if: steps.check-title.outputs.match == 'true'
        run: |
          docker pull ${{ github.event.issue.title }}
          docker tag ${{ github.event.issue.title }} ${{ secrets.DOCKER_USERNAME }}/${{ steps.check-title.outputs.image_tag }}

      - name: Login to docker hub
        if: steps.check-title.outputs.match == 'true'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push image to docker hub
        if: steps.check-title.outputs.match == 'true'
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ steps.check-title.outputs.image_tag }}

      - name: Add docker hub description
        if: steps.check-title.outputs.match == 'true'
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/${{ steps.check-title.outputs.image }}
          short-description: "mirror of ${{ github.event.issue.title }}"

      - name: Close issue
        if: steps.check-title.outputs.match == 'true'
        uses: peter-evans/close-issue@v1
        with:
          comment: |
            Image has been uploaded to docker hub, use `docker pull ${{ secrets.DOCKER_USERNAME }}/${{ steps.check-title.outputs.image_tag }}` to pull the image.
